import "./globals.css";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
  title: "NextToon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="border border-red-500 max-w-[80vw] m-auto">
        <Navbar />
        <div>{children}</div>
      </body>
    </html>
  );
}
