import "../styles/globals.css";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import { ReactQueryProvider } from "../utils/ReactQueryProvider";
export const metadata: Metadata = {
  title: "NextToon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReactQueryProvider>
      <html>
        <body className="w-[70vw] m-auto">
          <Navbar />
          <div>{children}</div>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
